# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180308_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocpage',
            name='video_link',
            field=models.TextField(blank=True, null=True, verbose_name='Link to video'),
        ),
    ]
