# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0001_initial'),
        ('blog', '0003_pocpage_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocpage',
            name='video_link',
        ),
        migrations.AddField(
            model_name='pocpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
