# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180308_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocpage',
            name='video',
        ),
    ]
