# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180308_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocpage',
            name='media',
        ),
        migrations.AddField(
            model_name='pocpage',
            name='video_url',
            field=models.TextField(blank=True),
        ),
    ]
