# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('blog', '0008_tagslistpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocpage',
            name='video_url',
        ),
        migrations.AddField(
            model_name='pocpage',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
